version: '3.4'
services:
  web:
    build: .
    volumes:
      - .:/var/www
      # Linking node_modules dir from container in order to have latest packages available
      - /var/www/node_modules
    environment:
      - PG_HOST
      - PG_USER
      - PG_DATABASE
    depends_on:
      - database

  database:
    image: postgres:9.4