version: '3.4'
services:
  web:
    command: >
      # Perhaps it will not be working in all machines.
      bash -c "yarn run build && yarn run serve"
    environment:
      - NODE_ENV=production
    ports:
      - 80:3000