version: '3.4'
services:
  web:
    build:
      context: .
      target: node_custom
    environment:
      - PG_HOST
      - PG_USER
      - PG_DATABASE
    depends_on:
      - database

  database:
    image: postgres:9.4