version: '3'
services:
  web:
    build: .
    volumes:
      - .:/var/www
    environment:
      - PG_HOST=database
      - PG_USER=postgres
      - PG_DATABASE=postgres
    depends_on:
      - database
  database:
    image: "postgres:9.4"