openapi: 3.0.0
info:
  title: Wob API
  version: 0.0.1

servers:
  - url: http://api.example.com/v1
    description: Production api server.
  - url: http://staging-api.example.com/v1
    description: Staging api server.

paths:
  /user:
    post:
      tags:
        - user
      summary: Signs up a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                confirmation:
                  type: string
              required:
                - email
                - password
                - confirmation
      responses:
        '200':
          description: Success sign up.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    get:
      tags:
        - user
      summary: Returns a current user.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: A JSON array of user names.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /user/password-reset:
    post:
      tags:
        - user
      summary: Sends password reset confirmation link to user email.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        '200':
          description: Success email sending.
  /user/password-reset/confirmation:
    post:
      tags:
        - user
      summary: Sets up a user password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                confirmation:
                  type: string
                token:
                  type: string
              required:
                - password
                - confirmation
                - token
      responses:
        '200':
          description: Success password change.
  /auth/sign-in/local:
    post:
      tags:
        - auth
      summary: Logs user into the system via local authentication scheme.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Success sign in.
  /auth/sign-out:
    post:
      tags:
        - auth
      summary: Logs out the user.
      responses:
        '200':
          description: Success sign out.

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string